# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
plugins_dir="plugins/"
auto_setup="false"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.41.2"
"rocks-git.nvim" = "2.5.1"
"rocks-config.nvim" = "3.0.0"
"conform.nvim" = "8.1.0"
"smart-splits.nvim" = {version = "1.6.0" }
nvim-web-devicons = "0.100"
nvim-lspconfig = { version = "1.0.0", event = "BufEnter" }
"telescope.nvim" = "scm"
"trouble.nvim" = { version = "3.6.0", cmd = "Trouble" }
"fidget.nvim" = { version = "1.4.1", event = "BufEnter" }
"oil.nvim" = "2.12.2"
"rocks-lazy.nvim" = "1.1.1"

[plugins.catppuccin]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins."mini.nvim"]
git = "echasnovski/mini.nvim"
rev = "v0.9.0"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"
branch = "master"

[plugins."lazydev.nvim"]
git = "folke/lazydev.nvim"
rev = "v1.8.0"
config = true
ft = "lua"


[plugins.nvim-vtsls]
git = "yioneko/nvim-vtsls"
rev = "45c6dfea9f83a126e9bfc5dd63430562b3f8af16"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"
rev = "cf48d4dfce44e0b9a2e19a008d6ec6ea6f01a83b"
branch = "main"
build = "make"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"
event = "BufEnter"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0^{}"
event = "BufEnter"

[plugins.nvim-ts-autotag]
git = "windwp/nvim-ts-autotag"
rev = "e239a560f338be31337e7abc3ee42515daf23f5e"
event = "InsertEnter"

[plugins.nvim-ts-context-commentstring]
git = "JoosepAlviste/nvim-ts-context-commentstring"
rev = "375c2d86cee6674afd75b4f727ce3a80065552f7"

[plugins.nvim-treesitter-textobjects]
git = "nvim-treesitter/nvim-treesitter-textobjects"
rev = "bf8d2ad35d1d1a687eae6c065c3d524f7ab61b23"

[plugins."telescope-import.nvim"]
git = "piersolenski/telescope-import.nvim"
rev = "abce03c71791bd27fc9043b62b5483467875b758"

[plugins."substitute.nvim"]
git = "gbprod/substitute.nvim"
rev = "v2.0.0"
event = "InsertEnter"

[plugins."yeet.nvim"]
git = "samharju/yeet.nvim"
rev = "v1.2.1"
event = "BufEnter"

[plugins.harpoon]
git = "theprimeagen/harpoon"
rev = "harpoon2"

[plugins."dressing.nvim"]
git = "stevearc/dressing.nvim"
rev = "v3.0.0"

[plugins.nvim-surround]
git = "kylechui/nvim-surround"
rev = "v2.3.0"
event = "InsertEnter"

[plugins."no-neck-pain.nvim"]
git = "shortcuts/no-neck-pain.nvim"
rev = "v2.0.6"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "00ba9dd3df89509f95437b8d595553707c46d5ea"

[plugins.nvim-treesitter-endwise]
git = "rrethy/nvim-treesitter-endwise"
rev = "8b34305ffc28bd75a22f5a0a9928ee726a85c9a6"

[plugins."grug-far.nvim"]
git = "magicduck/grug-far.nvim"
rev = "4e7e61d9a777ee11550ff396080abe295fcc98fe"
cmd = "GrugFar"

[plugins."which-key.nvim"]
git = "folke/which-key.nvim"
rev = "v3.9.0"

[plugins."blink"]
git = "saghen/blink.cmp"
rev = "v0.5.1"

[bundles.treesitter]
items = [
  "nvim-treesitter",
  "nvim-treesitter-textobjects",
  "nvim-ts-context-commentstring"
]
event = "BufEnter"

[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-fzf-native.nvim",
  "telescope-import.nvim"
]
cmd = "Telescope"
